[project]
name = "disfurbia"
version = "0.1.0"
dependencies = [
    "asyncio>=3.4.3",
    "bleak>=0.22.3",
    "fastmcp>=2.5.1",
    "nest-asyncio>=1.6.0",
    "pygame>=2.6.1",
    "pyyaml>=6.0.2",
]
